name: ph_sentiment
version: '1.0.0'
config-version: 2

profile: ph_sentiment

model-paths: ["models"]
test-paths: ["tests"]
macro-paths: ["macros"]

target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  ph_sentiment:
    staging:
      +materialized: view
      +schema: staging
    marts:
      +materialized: table
      +schema: marts
